### ISSUE TITLE
Shore Foam Edge Blend

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#10]
While ocean itself blends into shores quite nicely, foam looks a bit sharp on intersection.
Is it possible to soften the edge via blending like in unitywater4? Just thought it may give some extra smoothness to the picture.

![2018-05-10 20 58 30](https://user-images.githubusercontent.com/15368122/39885303-ea8a439c-5494-11e8-9f88-aac0e86838bb.png)

**Comment by Midda-C** [comment]
Yeah using a depth blend or something to just soften the edges would be great.

**Comment by huwb** [comment]
Thanks guys, agreed. I added a slight feather. I went ahead and pushed it as i think it is already an improvement. And i could reuse data im already sampling in the shader, so thats a good result!

Is this what you guys had in mind? Let me know.

![image](https://user-images.githubusercontent.com/939901/40268476-b95de77e-5b65-11e8-98ef-581b51686610.png)

**Comment by Midda-C** [comment]
Yep, that's basically what I was thinking.  Works well on the foam, however it doesn't look like the actual water surface itself is being feathered on the edge.

![image](https://user-images.githubusercontent.com/37893722/40269328-90599746-5bc0-11e8-9f93-dcec33f0eba8.png)

Any chance it could go to completely transparent at the very edge there?  Also, a property on the material to adjust the fade distance would probably be needed so projects of different styles/looks can get the result they desire.

**Comment by huwb** [comment]
oh interesting. i think it does, in terms of scatter colour (blueness). but the sharp shading difference you see is due to the water reflecting the sky etc. in this case i'm not sure if it would be appropriate to blend the reflectivity.

probably what is weird is that the land is not wet. if the land was wet then it would be shiny like the water and probably make this less jarring. the landscape could sample the water height and probably do something to simulate wetness, i could explore this if interesting?

**Comment by Midda-C** [comment]
> oh interesting. i think it does, in terms of scatter colour (blueness). but the sharp shading difference you see is due to the water reflecting the sky etc. in this case i'm not sure if it would be appropriate to blend the reflectivity.

Oh right, so you're not using regular alpha opacity to achieve the transparent effect?  If not, that makes sense.  Fading using opacity would (I think) fade out the reflection as well as a result.

> probably what is weird is that the land is not wet. if the land was wet then it would be shiny like the water and probably make this less jarring. the landscape could sample the water height and probably do something to simulate wetness, i could explore this after looking at the lighting/foam stuff if interesting?

Yeah I didn't think of that, the land being wet would also mask it, if their reflectivity was approximately equal at the water's edge.  I assume you'd have to do that on the land shader though, correct?  Our terrain is procedurally generated, so we have a fairly complex customised terrain shader to work with that, so I guess we'd need to duplicate that in our shader ourselves (and by we, I mean Dizzy :P).  But yeah, as a general solution, that sounds good.

Of course, @GeorgeDziov submitted this issue, so I don't want to just hijack it.  What's your take, @GeorgeDziov?

**Comment by GeorgeDziov** [comment]
@Midda-C you read my mind in previous post and @huwb wet shore idea is fantastic, I'm all hands for that one!

Regarding foam itself - maybe make foam a bit closer to shore so blue part on the edge is less visible or add a foam to shore distance property? Thought of that because most projects have different world scale so while shore foam looks perfect at one scale it may look a tad too far in another just like in screenshots above.

I'm also really tempted to say yes to some veeery small almost unnoticeable reflection blending to hide it under foam (hope my suggestion doesn't sound too ridiculous).

offtop: btw where can I ask non-issue water/ocean stuff? Is email ok?

**Comment by dizzy2003** [comment]
Re wet terrain, a few handy functions that we can paste into the terrain
shader would be great.

For each pixel you would need to know how long it was since it was last
under the water height.

Just thinking on the fly if the world was rendered plan view, with the
terrain renderered first just to the z buffer then the water rendered white
doing a z test. then every white pixel is wet.

This texture is faded out a bit each game turn, with effectively any pixels
under the water reset to white.  (the two textures need to be combined, the
faded and the fresh one with a max blend)

This would give a world space texture that can be sampled  to apply any
needed darkening/increase in shinyness for wetness
