### ISSUE TITLE
Build not showing foam

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#105]
Do a build and the foam will be missing.  I think this is the shader stripping issue coming back again.

I tried including the ocean shader into the list of shaders to always include however the system tried to create over 1,000,000 shader varients from that so had to kill that.  Trying to include like the ShapeSimFoam to see if that is missing.  If so I am not sure if others should be include etc  as well.  

Only guessing right now that this is the issue.

**Comment by huwb** [comment]
Wow, turns out i dont know how shader features work.

They cant be driven by code, they need to be toggled on the material, so I undid my recent changes and moved them back! But i've added a warning if the required feature is disabled so at least it should be less error prone.

Thanks for reporting!
