### ISSUE TITLE
Main scene in examples doesnt work anymore?

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#135]
I'm using unity 2018.2.17f1

Loading the main scene from examples looks like the ocean material isnt assigned nor any of the scriptable objects for foam etc.

Also had errors with Post Effects

the boat scene seems fine though.

**Comment by huwb** [comment]
Hm ok. Sometimes i need to restart unity and/or delete the library folder, thought I'd mention in case its unity being funny?

I should have time to try repro this tonight.

**Comment by huwb** [comment]
Ok i got the postproc error on a different computer and pushed a fix for it - was forced to enable a whole bunch of packages due to some messy dependencies. Not sure why it didnt happen on my laptop. Oh well.

If you still get the unassigned material or other issues and have any more info for me let me know?

**Comment by huwb** [comment]
I've not heard any other issues so assuming fixed, let me know if something is still broken though
