### ISSUE TITLE
no waves on switch

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#136]
tried the boat demo on switch, the waves dont appear to work, obviously its not a lot to go on at the moment, but heres a screenshot of the sim data enabled.

BTW running the crest boat demo as is on switch, at 720p with switch in fastest mode, camera post processing disabled gives a cpu time of 6.5ms and a gpu time of 11.7 ms

![xal02100112553-20181205-0002](https://user-images.githubusercontent.com/15023384/49494459-7c1a6200-f8ab-11e8-9fbe-fecfd3f5981d.jpg)

**Comment by huwb** [comment]
Ah that looks like an issue from the latest refactor (i assume you're on latest and "greatest"?), I can repro that here. I hope to have a look at this this evening. It looks like the shader feature defines in ShapeCombine.shader don't work in standalone builds and a hackfix might be to comment these out so that the dynamic waves are always added.

Re perf, good to know thanks. Thats higher than i would have expected, especially on the CPU side. I'd love to see more detail on this if you get a chance to grab it.

**Comment by huwb** [comment]
Pushed a proper fix, should be sorted now. Apologies for that.
