### ISSUE TITLE
Misbehaving masking of terrains in Deferred Render mode with the stencil function.

### ISSUE THREAD

**Issue by No-Half-Measures** [huwb/crest-oceanrender#142]
Slight Bug with terrains and the new stencil function, If your camera's Rendering Path is in the Deferred mode and the Render State Stencil Function is enabled on the ocean material it will stencil out the terrains area.

**Comment by huwb** [comment]
Hm i could not repro this. I added a terrain to the boat.unity scene and set the camera to deferred and put a sphere with the mask using stencil but the terrain still renders through.

![image](https://user-images.githubusercontent.com/939901/49763933-f68d1c80-fcc5-11e8-968d-b32698511c0a.png)

**Comment by No-Half-Measures** [comment]
This was on Unity Version **2018.2.8f1** just upgraded to **2018.2.19f1** this morning and reproduced this again this time in the boat scene. In the *Ocean* material you need to enable the *Stencil Function* this is enabled in the *Ocean-Underwater* material used in the main scene.
![image](https://user-images.githubusercontent.com/916733/49802014-afde0780-fd43-11e8-801d-8c1f26733a85.png)

**Comment by huwb** [comment]
Right i could repro it now, not sure what i did wrong before.

Yeah this seems like a collision with Unity's use of the stencil buffer in deferred mode: https://answers.unity.com/questions/956062/unity-5-deferred-stencil-buffer-usage.html

I'm reopening #77 and will refer to this issue from there so that the issues are linked. Lets move this discussion there.

Thanks for reporting!
