### ISSUE TITLE
WaterMask disappears when camera inside

### ISSUE THREAD

**Issue by ecelstyle** [huwb/crest-oceanrender#163]
Is there way to ocean not render in some areas. Like boat inside.

**Comment by ecelstyle** [comment]
Ok, i will focus on this subject now, i need to fix it. 

Is there a way can we implement this feature like displacementMap or Foam? Maybe we can add another texture for masking, and draw surface transparent? So shader code will be easy, then we try to update this mask texture with boat's collision with the ocean.

I have an other water shader solution, we were using it, that asset has substract volume feature, maybe i should check it, and try to implement it. But it's performance 3x slow..

**Comment by huwb** [comment]
Yes you could add a new lod data type and the system should allow this without too much trouble (but will take coding). But if the shape is not a perfect match, you may see cracks and mismatches and stuff and it could get ugly. It will depend on the resolution.

I think I would stick to what i suggested above, if it was me.

**Comment by ecelstyle** [comment]
> Yes you could add a new lod data type and the system should allow this without too much trouble (but will take coding). But if the shape is not a perfect match, you may see cracks and mismatches and stuff and it could get ugly. It will depend on the resolution.
> 
> I think I would stick to what i suggested above, if it was me.

You are right, I will stick with first suggestion

**Comment by ecelstyle** [comment]
using discard in the shader is a good approach, i started with a box shape. Then i tried capsule. The capsule was not a solution like my first box, cause boats have a weird shape as you know. I read lots of documents, i wanted to use convex collider, i was going to use ComputeShader for that, then i lost in this. Thats why I decided to combine that first two options together, if i enter the boat, i disable Mask and enable simple shape discarding method, people can't see boat's hull outside that contract with ocean, so if he walks out of boat I enable mask again and disable discarding? So the player can see water contracting with the boat as excepted. This is just a solution for my project, so I'm just giving the idea if someone likes this solution for their project. But we can't implement this ugly solution for the Crest. What do you think?  

> I checked my previous depreciated water asset they have two volume shader variant for if camera inside of mask or out of the mask. If you want to check it out the difference of this shaders I can send it to you. Volume Back Depth and Front Depth named.

**Comment by huwb** [comment]
Thanks, i think i understand what you did. So you discard from the fragment if you're inside, otherwise you use a depth mask. If you can post images of these two situations it would be nice to see, but no worries if not.

If you did need the discard to match the shape more closely, it should be possible to model a range of shapes (not just capsules etc), similar to https://www.iquilezles.org/www/articles/distfunctions/distfunctions.htm

I'm not sure about incorporating into crest, its not that i think its particularly ugly, but its quite bespoke/custom (and i dont have an appropriate asset to demo it) and i think having this thread is enough for now.

I did not quite understand about the deprecated water asset, is it something you made or the unity one, or something else? If its something from the asset store then its best that you don't send it to me as I don't want to see code that im not permitted to use.

Thanks for posting the update, really useful!

**Comment by huwb** [comment]
Btw i'm hoping to build a gallery of thumbnails for projects using crest on the readme. If you get to a point where you could upload something to youtube and are happy for me to link to it, please let me know. It would be great to showcase this kind of advanced use case.

**Comment by ecelstyle** [comment]
Thank you for your help. Distance functions link is a really nice source. I'm working on a proper fragment discarding pixels, after finding a solution i will share with you guys. I will share thumbnails/videos soon for your share, we are proud of it. 

Is there a way to render underwater (like underwater window) edges of fragment hole? You can see it in white

![image](https://user-images.githubusercontent.com/46430090/52694588-44026000-2f7b-11e9-907d-ead23e01ffa4.png)

**Comment by huwb** [comment]
Not currently, but I guess I'd put four inward facing "windows" to make walls in the hole
