### ISSUE TITLE
Support for Shader adjustment/Code Review?: to combine Planar Reflection with Cubemap based Reflections

### ISSUE THREAD

**Issue by gameanimation3d** [huwb/crest-oceanrender#175]
Hey,
i wanted to combine Planar Reflection with the Cubemap Reflection as skybox reflection get turned off on Planar Reflection.
I adjusted the OceanReflection.hlsl and it worked kind of but is still have some issue.
I am using the Crest 5 Release Version
I followed this guide (https://community.arm.com/graphics/b/blog/posts/combined-reflections-stereo-reflections-in-vr) and tried my best to get it working

The Cubemap Reflection has some nice little reflection details:
![onlycubemapreflection](https://user-images.githubusercontent.com/44543590/51703086-bbe10880-2015-11e9-8949-d4f834460659.JPG)

But the Planar is just flat
![onlyplanarreflection](https://user-images.githubusercontent.com/44543590/51703110-ca2f2480-2015-11e9-9792-3e1a21cd49f9.JPG)

combined:
![combined_issue](https://user-images.githubusercontent.com/44543590/51703138-dc10c780-2015-11e9-939a-14d933606a18.JPG)

I hope you can give me a hint what i did wrong, i basically hacked it together.
I don't if this already maybe solved in #172 

I attached the whole hlsl file as txt file: 

[OceanReflection_v02.txt](https://github.com/huwb/crest-oceanrender/files/2793280/OceanReflection_v02.txt)

but here the important changes to it i made to ApplyReflectionSky() 

	half4 PlanarReflection(half3 refl, half4 i_screenPos, half3 n_pixel)
	{
		i_screenPos.xy += n_pixel.xz;
		float4 dynReflTexCoord = UNITY_PROJ_COORD(i_screenPos);
		return tex2Dproj(_ReflectionTex, dynReflTexCoord);
	}

	
        void ApplyReflectionSky(half3 view, half3 n_pixel, half3 lightDir, half shadow, half4 i_screenPos, inout half3 col)
        // Reflection
        half3 refl = reflect(-view, n_pixel);
	half4 skyColour;
	skyColour = texCUBE(_Skybox, refl);
	float4 dynReflColor = i_screenPos;
	#if _PLANARREFLECTIONS_ON
		skyColour = texCUBE(_Skybox, refl);
		dynReflColor = PlanarReflection(refl, i_screenPos, n_pixel);
	#elif _PROCEDURALSKY_ON
		skyColour = SkyProceduralDP(refl, lightDir);
	#else
		//skyColour = texCUBE(_Skybox, refl).rgb;
	#endif
		

	//Combing reflection
	dynReflColor.rgb /= dynReflColor.a;
	float4 reflCombiColor;
	reflCombiColor.rgb = lerp(skyColour.rgb, dynReflColor.rgb, dynReflColor.a);
	reflCombiColor.a = 1;

	skyColour = reflCombiColor;
	//END Combining

Missing is here last part in the guide regarding changes in the fragment shader.

> The final fragment color can be replaced by the below line:
return _AmbientColor + lerp(reflCombiColor, texColor, _StaticReflAmount);

**Comment by huwb** [comment]
Hi there, I'll dip in her, but i should state up front that i don't have the resources to provide general dev services, maybe someone else is up for collaborating with you? We could apply the help wanted tag and see if anyone bites if you would find that useful?

I did however take a look at the above. My first immediate question is about the reason for this change:

> i wanted to combine Planar Reflection with the Cubemap Reflection as skybox reflection get turned off on Planar Reflection.

I'm not sure i follow.. The skybox should be included in the planar reflections. If you enable the ocean planar reflections in the main.unity scene, the reflection should include the sky. Perhaps this is a scene setup issue.

If i understand you correctly when you say "details" - the amount of distortion in the reflection (?) - it might be worth simply ramping up the offset (computed from normal) to make the distortion greater, so multiply up this:

i_screenPos.xy += n_pixel.xz;


Finally a few immediate things that i noticed when i looked at the code:

* The divide by alpha looks worrying - what if the alpha value is 0?
* Is the alpha channel correctly assigned in the dynamic reflection image (i guess it wants to be 1 where objects are rendered and 0 otherwise)? I'm not suggesting it isn't but its something i would check if you havent already using the frame analysis in unity or renderdoc.
* I assume you've set up your scene appropriately so it will support this fallback behaviour (i guess you only want the duck rendering into the dynamic reflection texture and everything else should fall back to the env texture.

**Comment by huwb** [comment]
Oh and i believe 172 does not affect this issue, i think this bug was introduced after version 5 and it doesnt look to be present in your screenshot and code.

**Comment by gameanimation3d** [comment]
Hey thank you very much for the answer:

`Hi there, I'll dip in here, but i should state up front that i don't have the resources to provide general dev services, maybe someone else is up for collaborating with you? We could apply the help wanted tag and see if anyone bites if you would find that useful?`
Sure your are bussy no Problem. But think your answer solved the "issue" or my misunderstanding.

`If i understand you correctly when you say "details" - the amount of distortion in the reflection (?) `
It's hard to describe on one hand its the distortion in the reflection but also the depth(normal map?) in the water the small little "ripples". 

Nevertheless multiplying the distortion in the shader helped.
But the key misunderstanding from my side was that after Enabling the  Planar Reflection the Skybox Material in the Ocean Shader/Material doesn't do anything anymore. Only the Skybox Material in the Lighting affects the ocean.

As i think in the .hlsl shader it get switched between the texturing ocean surface with the skybox or calling PlanarReflection Function.

`      #if _PLANARREFLECTIONS_ON
	skyColour = PlanarReflection(refl, i_screenPos, n_pixel);
      #elif _PROCEDURALSKY_ON
	skyColour = SkyProceduralDP(refl, lightDir);
      #else
	skyColour = texCUBE(_Skybox, refl).rgb;
      #endif`

I was adding at runtime a cubemap from an reflection probe into the shader for nicer reflections. With Planar Reflection enabled it's useless but adding it into skybox material solved it :+1:

**Comment by huwb** [comment]
Great, happy to hear that!
