### ISSUE TITLE
Tweaking chop value per wave spectrum

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#18]
At the moment, the chop value is a shared value across the whole of the simulation.  I'm finding that at some wave frequencies, I'd like to have a different choppiness to others.  Is that feasible at all?

Maybe a checkbox next to each level of the wave spectrum to let you override the chop from the global value to a user-defined one?  It'd also be nice to set it to values greater than 1 like what your debug GUI allows for.

Also, a sidenote, it seems odd that the chop is currently specified in a different section to the actual wave spectrum.  Is that intentional?

Thanks!

**Comment by huwb** [comment]
Ha thats interesting, i had not thought of this. There are historical reasons why chop is all-up, but not great ones. I've had a few different kinds of shape in the past and they all shared the same chop value, but i think it should be broken out per shape type.

What you propose could make sense - adding it to the wave spectrum as an option, for each wavelength if i can make it work elegantly.

There is a snag that prevented me from just doing this right now - the global chop value is used to compute the potential bounding box for an ocean tile, I need to make this a bit smarter before i can remove the global setting. I'll post when i have news.

**Comment by huwb** [comment]
So i removed the global chop value and it actually improved the code - I'm not measuring the bounding box based on the actual shape. When the ocean is calm, this will make the bounding boxes tight and it will render more efficiently. So that was a win on all accounts!

The chop value is now on the spectrum component. I havent broken it out per octave just yet. I'm mulling over how to do this without adding complexity to the ui and code. With my latest changes i just pushed its possible to emulate this feature by duplicating the Gerstner shape gameobject and making them render complimentary octaves, and you can then tweak the chop. If you do happen to get latest I'd be interested if you can confirm this per-octave chop is indeed useful.

Anyway i'll think about it on my side and will post back if I find a nice way to implement it.

**Comment by huwb** [comment]
Hey Midda! Thought I'd bump this one. I did have a play with breaking out chop per octave, commit linked above. I wasn't happy with it so far so its currently on pause.

My note about complimentary octaves may not have been clear. I'm referring to duping the render gerstner waves GO and selecting mutually excusive sets on multiple wave components, which allows to set different chop values. One could look like this:

![image](https://user-images.githubusercontent.com/939901/41274857-d8992ed2-6e16-11e8-877a-edc8d1989aba.png)

If the octaves are complimentary then it should not double up on work/expense.

I'm not sure the above is a good solution, but it might allow to test a bit more with the extra control over chop, it would be good to confirm that you're getting a good benefit out of this to motivate further investigation.

**Comment by huwb** [comment]
Cool! Could you give me some info on what you did and why? Did you boost the chop value across the board to exaggerate horizontal motion on all wavelengths, or just some of them?

Will be interesting to hear when you do get to that stage. Actually i think a number of things will want to change to support multiple ocean, such as saving out spectra as assets and potentially rendering them in localised areas. I should probably make the former change sooner rather than later, might mess with it in the next days.

**Comment by huwb** [comment]
While experimenting on something I looked at artificially sharpening the waves a bit. This is no longer physical which I'm generally not a fan of - it adds some fast vertical velocities and makes the surface move in a slightly different way. But it gives a bit of extra control and might be interesting? If it is I could look at pushing a version that you can play with, let me know.

https://drive.google.com/open?id=12jT5Tb7E4E9HOBb78uJ00k7h-OBPD7PH

**Comment by huwb** [comment]
(oh and you'll notice the sea level drops a lot - this is due to the shape modification - it essentially pushes the troughs down in order to make the crests sharper, and this has the affect of lowering much of the ocean surface..)

**Comment by Midda-C** [comment]
Interesting, thanks.  Judging from the clip, it looks like it's a replacement for the existing chop, is that right?  Or is it something that layers on top of the existing method?

**Comment by huwb** [comment]
To illustrate, the image shows conceptually what I'm doing - I apply an exponent to the wave (orange) to get a new, slightly weird function (blue) which is a bit sharper

![image](https://user-images.githubusercontent.com/939901/43361134-481a4a76-92bf-11e8-8105-de296a15e231.png)

**Comment by Midda-C** [comment]
Ah yes, I wondered if it might have just been an exponent.  I'd certainly be keen to try it out.  I do think though we'd probably need to account for the apparent lowering of the sea level, though.  Our world generation expects the sea level to be at a certain height (otherwise we'll have some rocks and reefs sticking out of the water).

**Comment by huwb** [comment]
Probably not highest priority but if you get around to it, i have pushed a new branch feature/sharp_gerstners (commit shown above), which has a Sharpen Exponent parameter added to the wave spectrum (next to chop). I was able to solve the height change issue by ensuring average height across the waves is maintained.

**Comment by Midda-C** [comment]
So I just had a look at the sharp_gerstners branch, and it works pretty well.  Seems like a nice way to get that little bit of extra sharpness on the peaks without getting that horizontal clipping which happens when the chop is too high.

We'd probably make use of it, and I expect others might too.

**Comment by huwb** [comment]
I've fiiiiiiiinally exposed per-octave chop as a test. Since per-octave speed was also requested in #41, i decided to add both.

The new options are tucked away behind the Advanced Settings toggle on the ocean wave spectrum, on the *feature/per_octave_settings* branch for now. These changes will add a small extra expense so it would be good to confirm this is useful before committing to master.

My initial experiments seem to give positive results. Adding chop to just the smaller wavelengths can avoid some of the unnatural horizontal motion. It also gives a nice control over foam (because choppy water generates foam).

If you have a chance to process this, let me know. We can discuss the other wave sharpening approach as well at some point. Both of these approaches will add a small expense, although its likely pretty minimal, but it would be good to be sure about stuff before adding it.

**Comment by Midda-C** [comment]
Great!  I just had a quick play with the changes (just a few minutes), and it seems really powerful so far!.  Currently, we've got two separate Shape Gerstner Batched scripts with different spectrum assets on there, but in the little bit I've played with this, it looks like we should be able to just go back to the one file.

Yeah, you're able to avoid that strong horizonal motion now by isolating the high chop to the smaller wavelengths, without having to have multiple spectrum files.  Nice!

The speed is handy too.  One thing which might be good is to have a global speed slider, like we do with the chop.  I assume the chop scale sliders are a multiplier over the main chop value at the top?  It'd be good to have that for the speed too.  It doesn't add any extra functionality, but it woule mean you could quickly set a base speed for all wavelengths and then just tweak accordingly.

The additional cost that you mentioned, is that only there if the "Show Advanced Controls" option is ticked?  Or is it always there now?  Any idea how significant that is?

**Comment by Midda-C** [comment]
Yeah, I noticed today that the advanced control option is bascially just a UI option.  But that's good!  It meant I could go in there and adjust the chop on a few different resolutions, then hide it all again to just adjust the sliders like before.

**Comment by huwb** [comment]
Yeah thats cool. I tweaked the UI a bit to hopefully make it less programmer-art-y . Despite spending quite a lot of time making editor GUIs i never really became good at it!

The wave sharpening approach - I'll leave it on ice?

An easy optimisation occurred to me, i could put this stuff on static switches, like the Ocean.shader options. I think its pretty easy to turn features on or off dynamically, i.e. only when the defaults are overridden. I'll leave that for future work for now though.

**Comment by Midda-C** [comment]
The sharpening has some merit, it might have some use somewhere down the line, but it's probably not needed for this.  It might be better to leave it out, in the interest of not overwhelming users with too many options.

Could maybe be used to sharpen the dynamic waves or something?

**Comment by huwb** [comment]
Maybe it is possible to sharpen dynamic waves. I did an experiment here where i shift the points horizontally based on the gradient of the height - this can actually convert a sin wave to a gerstner/trochoid wave (provably), which i had not thought of before. But most relevant for us, it might work on arbitrary shape, as demo'd here:

https://www.shadertoy.com/view/ltcyDX

Blue is the original function (could come from the dynamic wave sim), white is the sharpened result. You can see the result is not perfect (there are some curvature issues), i'm not sure how it will look from the wave sim. Seems worth trying though, i'll post back if i get a chance to try it.

**Comment by huwb** [comment]
I'm happy to report that i have a prototype implementation pushed and I think this might have legs - I have opened a new issue for it: #47 

If you could try it out at some point I'd love to hear if you think it is usable!
