### ISSUE TITLE
Adding alpha var to RenderAlphaOnSurface

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#180]
It seems useful to be able to control the alpha setting on RenderAlphaOnSurface.  This is so we can do fade outs etc unless you can think of a better way.  I keep changing this file so figured I would ask if can just get it added.  Thanks.

  public float Alpha = 1;

in lateupdate

         _mpb.SetFloat("_Alpha", Alpha);

**Comment by holdingjason** [comment]
Oh also maybe a helper function someplace to get height at position.  I keep adding this to OceanRenderer as well.  Again you might have a better idea but use this a fair amount.

  public float GetWaterHeightAtPosition(Vector3 position)
        {
            float height = 0;
            var r = transform.lossyScale.magnitude;
            var collProvider = OceanRenderer.Instance.CollisionProvider;
            var rect = new Rect(new Vector2(position.x - r, position.z - r), 2f * r * Vector2.one);
            if (collProvider.GetSamplingData(ref rect, 2f * r, _samplingData))
            {
                var pos = position;
                if (OceanRenderer.Instance != null)
                {
                    collProvider.SampleHeight(ref pos, _samplingData, out height);
                    collProvider.ReturnSamplingData(_samplingData);
                }
            }
            return height;
        }

**Comment by huwb** [comment]
Hey, I'm unsure about the former because then it will be driving from code a parameter on the material that an artist may want to tweak, it will be confusing in this case if the code stomps over it. An option would be then to hide it from the material gui to avoid this confusion, but im not sure this is my intention. I'd be inclined to leave it as it is and suggest that if you want to drive it from code, drive it directly to the material from the code that cares about it. An (inefficient) example:

MyScriptThatWantsTheAlphaChanged.cs:
...
    theAlphaObject.GetComponent<Renderer>().material.SetFloat("_Alplha", whatever);

**Comment by holdingjason** [comment]
No problem.  Close it out.  You're right was not really thinking about it
clearly

**Comment by huwb** [comment]
The latter is intentional because GetSamplingData() is a nontrivial operation (in particular if using displacement textures, in which case the code must seek out the lod index that provides the desired data), so it is supposed to make calling this function a conscious decision (and if possible call it once for multiple queries). However if there are lots of disparate single queries i can see how it would be tedious. I could make a function like this and give it a name and comment that implies its for single queries only and can be expensive, would that make sense?

(Minor request - in the future could we not mix issues together like this as it makes my OCD flare up :), and it will make it hard for me to organise and refer back to discussions which i frequently do.)

**Comment by holdingjason** [comment]
Sure all that makes sense. Again I think I was not thinking about the
expense so I need to double check my code and see if I really should be
doing this, this way, or should try and combine these.  Would be bad based
on what you said to do a lot of these septate calls be batching them so I
can see why you did not create a function for this

**Comment by huwb** [comment]
Well, I'll close but feel free to post back here after you think about it. I'm not against making that change i mentioned if you think its helpful.

**Comment by holdingjason** [comment]
Thanks.  No problem.  New information or was not thinking about it correct
