### ISSUE TITLE
PS4 rendering broken with deferred camera (depth read fail)

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#193]
Turns out that ps4 is binding the in use compressed depth texture to _CameraDepthTexture

so ocean shader is reading a garbled mess when reading this texture.

Apparently to avoid this it seems you shouldnt read and write to the z buffer  in the same shader
(see tips and tricks)
https://docs.unity3d.com/Manual/SL-CameraDepthTexture.html

Disabling z write causes some issues with gaps between the quads (not sure why, are some filler meshes being added that require z test equals?) but theres also the obvious z sort issues too.

I imagine I might have to draw the ocean as a sort of z pre process that writes to the z buffer to fix the issue.

**Comment by huwb** [comment]
It's usually not an issue because it's reading from the primary depth texture, and writing to another depth texture.

I'm not sure why this is not working on PS4 but I'll think about it

**Comment by huwb** [comment]
What is bound as the depth texture - is it a resource that has a name or any other clue? Also what exactly is bound as the depth buffer? If there are names or other clues it might help to figure out out.

Also do you have any image effects that also use the primary camera depth, such as DOF? If it does work could you compare what is bound for reading with what is bound for reading and what is bound for writing during ocean render?

**Comment by huwb** [comment]
Finally, this is a long shot, but you haven't changed the queue for the ocean shader by any chance? If it's scheduled before 2500 then camera depth will not be avail

**Comment by dizzy2003** [comment]
will send you a private email with some ps4 specific info

**Comment by huwb** [comment]
@dizzy2003 found ps4 unity forum posts from some time ago which appear to confirm that, on ps4, _CameraDepthTexture will point to the primary depth buffer which is bound, and you can end up reading and writing to the same memory at the same time! How exciting.

He found a solution that seems to work for the crest example content and he gave me permission to post it here.

This code adds a command buffer to the AfterGBuffer event (use AfterForwardOpaque in forward rendering) which saves out a copy of the depth buffer after rendering opaque objects, and then binds this copy to a new sampler called _DepthBuffer:

`
            Camera cam = Camera.main;
            int depthID = Shader.PropertyToID("_DepthCopyTexture");
            CommandBuffer cmd = new CommandBuffer();
            cmd.GetTemporaryRT(depthID, cam.pixelWidth, cam.pixelHeight, 0, FilterMode.Point, RenderTextureFormat.RFloat, RenderTextureReadWrite.Linear);
            cmd.Blit(null, depthID, m_BlitDepthMat);
            cmd.SetGlobalTexture("_DepthBuffer", depthID);
            cam.AddCommandBuffer(CameraEvent.AfterGBuffer, cmd);
`

He then uses this copy of the depth texture instead of _CameraDepthTexture if `UNITY_PS4`
and if `SHADER_API_PSSL`.

m_BlitDepthMat from above is this shader:

`
Shader "BlitDepthShader"
{
    SubShader
    {
        // No culling or depth
        Cull Off ZWrite Off ZTest Always

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
            };

            struct v2f
            {
                float2 uv : TEXCOORD0;
                float4 vertex : SV_POSITION;
            };

            v2f vert (appdata v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = v.uv;
                return o;
            }

            sampler2D _CameraDepthTexture;

            float frag (v2f i) : SV_Target
            {
		float col = tex2D(_CameraDepthTexture, i.uv).r;
                return col.r;
            }
            ENDCG
        }
    }
}
`

**Comment by dizzy2003** [comment]
For whatever reason in our game I had to capture the depth buffer at CameraEvent.BeforeImageEffectsOpaque

(for both pc and ps4) to get any depth data in the texture.
