### ISSUE TITLE
Problem With Adding Geometric Shape

### ISSUE THREAD

**Issue by JiayiXuu** [huwb/crest-oceanrender#205]
Hi!

I have some trouble adding a custom geometric shape into the shader. We are working on rendering a high amplitude wave that spans across the LODs and could move forward at runtime. (Like the giant wave in Interstellar).

We successfully added the forward motion onto the water bump in your boat scene. However, when it moved across a certain distance, the amplitude of the shape slowly decrease to invisible. We guessed that the shape might be local within LOD, as confirmed in another post. 

To bypass the problem, we also displacing the shader vertex but it didn't seem to work. 

My question is: is there a way to expand the shape across LODs? If that is possible, how to add a shape that is not centered around a sphere, but to center around an x or y-axis?

If anyone has any thoughts on this please leave some feedback, thanks!

**Comment by huwb** [comment]
Hi there!

The bump from the boat scene is configured to render into a particular LOD, instead of rendering into all LODs. See the *Octave Wavelength* field. its set to 11, which is 2x the radius of the bump (so therefore the wavelength of the bump). This is an optimisation - instead of letting the system render the shape into all the lods, we hint about what sort of lod might be appropriate and then the system only renders it into a single lod.

Generally you want to set this field to the wavelength of you wave. However i just tried here and i'm encountering an issue so i'll need to look into it later. So for now, just set *Octave Wavelength' to 0 and it will render into all lods, which works for me with an enormous bump.

**Comment by huwb** [comment]
Btw thikning about interstellar - i think i know a trick to fake a
spherical ocean instead of a flat one, if this would be of interest let me
know. It's a dirty hack but it might work given enough commitment and elbow
grease :)

**Comment by JiayiXuu** [comment]
Thanks!! I just gave it a try and it worked in having a huge bump. I'll implement some more changes and see how it goes. 

A spherical ocean would be awesome! Our team talked about this but don't know how to do it. By all means please share with us, can't wait to get hands-on and see if it works!

**Comment by huwb** [comment]
Great!

Spherical hack. I called it hack everywhere, to emphasize that it is a hack. Check out the changes - you can see i've added a param for the radius of the sphere.

ff1d8943ed4946d939f3013b2733d11be1d28b22

I'm sure you will run into issues. I'd be interested to hear what they are in case i could make this a supported thing one day, maybe.

**Comment by huwb** [comment]
Right i fixed the issue i mentioned above - you should now set the 'octave wavelength' to be the wavelength in your wave. It will now render the large wave into only the last lod, and is therefore very efficient.
