### ISSUE TITLE
Creating Bow Wakes without moving the Ship

### ISSUE THREAD

**Issue by SilverbackKarthik** [huwb/crest-oceanrender#210]
Our project makes use of the Timeline and also requires Ocean. The Ship itself is a part of various parent constraints and should not be moving in the water. Though we have used a custom Flotation Component to make things float in water without requiring any physics.

What we want to achieve is Bow Wakes without having a moving ship. We want the water flow/direction to create the Bow Wake when it hits the ship and create an effect as if the ship is moving even though it physically isn't.

Also, it needs to be accompanied with Water Splash when the water hits the ship.
I am experimenting with the https://github.com/huwb/crest-oceanrender/tree/feature/wave-peak-fx to have it implemented with good visuals.

**Comment by huwb** [comment]
You should be able to achieve this using flow - if you pin the small boat
in place in the whirlpool example scene it should generate a wake from the
water motion (may need tweaking to make it more visible). What you're
describing sounds like that but with a simpler flow - constant in one
direction instead of circular. Let me know if that makes sense.

**Comment by huwb** [comment]
Hopefully this made sense. I'll close but will get notifications if you reply, and if theres an issue I'll reopen.
