### ISSUE TITLE
Possible to view a cross section of the ocean?

### ISSUE THREAD

**Issue by kinglouie** [huwb/crest-oceanrender#213]
I'm currently working on a 2.5D game which looks at a cross section of the ocean. Unfortunately most available 2.5D Assets e.g. [this](https://assetstore.unity.com/packages/vfx/shaders/substances/water-2d-tool-35521) are not well suited to render the water body into the horizon. I found some other issues like #163 but they're not quite the same.

It would be nice if there was either a feature to mask out the ocean but look into the cross section instead of hiding the ocean or simply let the ocean end in the z axis at a certain position.

**Comment by huwb** [comment]
Thanks. I think you understand correctly, there isn't a super nice way to do this currently. I want to explore this but I won't have bandwidth to do so in the short to mid term I'm afraid.

A brute force approach could be this which is probably what you were already aware of:

* Constraint ocean to move in x only (you can provide the viewpoint transform which it will follow around)
* Turn off half of the ocean chunks/tiles
* To see the cross section use something like the 'underwater windows' in #163

**Comment by kinglouie** [comment]
Thank you for pointing me directions :)

Constraining the ocean to not move in the z-axis and disabling half of the tiles is a good start that works nearly as expected. One issue is, that by the nature of the gerstner waves, the tiles exceed their rectangular boundaries so there is no clean cross section. Another issue with the underwater windows from your branch is, that they behave a little funky when they touch the ocean surface.

I will have a look into your great codebase and see if I can fix these issues by myself.

**Comment by huwb** [comment]
re gerstners, ah yes, that will happen. you might need to leave 'enough' of the tiles enabled so that they are always overlapping your cross section, and then cut them by adding a call to clip() in the Frag shader in Ocean.shader. This will kill the pixels when you give it negative values. If you want to cull any ocean surface that has a negative z coord, stick this instruction in:

clip(input.worldPos.z);

I think the funky behaviour is fixable as well. If you don't have luck sorting it you could post a screenshot.

**Comment by huwb** [comment]
yeah the tucking this is what it does for the curtain for the underwater effect, it works fine to have them overlap because the ocean surface should draw over the underwater curtain and hide the overlap.

i'm not sure about the left hand side thing, from visual inspection at least. is this is pushed somewhere (such as in a fork) then please post a link, in case me or someone else has time to mess around with it. anyway ill think about it and let you know if i have any ideas.

**Comment by kinglouie** [comment]
I just pushed a branch where there is a demo in the main scene.
https://github.com/kinglouie/crest-oceanrender/tree/feature/crosssection

**Comment by huwb** [comment]
I've not had time to look at it, sorry :(. How is it going? I will close this as I don't like to have issues open if myself or someone else is not having time to look at them, but I'll get notifications if you reply here. Also you might like to join the discord if you haven't already, linked from the main readme.
