### ISSUE TITLE
[Enhancement] Depth Cache Handle Multiple Material-IDs on an object.

### ISSUE THREAD

**Issue by karearea** [huwb/crest-oceanrender#234]
I noticed that the runtime generation of the depth cache images only handles the first material ID of a given mesh. I have a number of architectural items with many materials, and the depth cache only renders the first of those submeshes (This is in the LWRP version).

As an additional suggestion, spinning the runtime script off into an editor tool could be useful. I am considering authoring my depth textures using mesh intersections in 3D software, as I'd like to clean up some of the finer areas to improve the look of foam. If I could do this in Unity before runtime, and save out / edit a texture, this would be helpful. Certainly not a priority or 'need' though!

**Comment by huwb** [comment]
What version are you using? This is one of the things that varies significantly between standard pipeline and SRP.

Good shout about the editor tool, I'm not sure when I'd be able to get onto it though.

The values in the depth texture are geometry position Y value - 1000. So a value of 0 in the depth cache means "1000m deep". A value of 999 means 1m deep. This is because of arcane reasons in how crest fades lod data in and out, so 0 has to default to deep water.

**Comment by huwb** [comment]
Just realised a downside of the editor tool - the texture then need to be distributed with the game could take significant memory

**Comment by karearea** [comment]
The new approach works perfectly in LWRP, thanks! Agree on your last point too.
