### ISSUE TITLE
Grabbing wave heights via jobs JUST needs the ocean depth capture

### ISSUE THREAD

**Issue by KellanHiggins** [huwb/crest-oceanrender#253]
I am trying to reverse engineer the ocean texture depth but it is beyond my technical abilities. Reading from the texture cache anything below 1000 is reading the same number as the water at zero height. 

Changing the max terrain height also messes around with these numbers in unpredictable ways. The range from a depth of 0 to 1000 is between 0.2343786f & 0.3898833f for some reason and it looks to be on a log curve if I try to normalize it. 

I am not familiar enough with shader code to understand how the depth numbers are being pulled from the textures. 

If anyone has the know-how find me how to read the texture cache heights this feature should be done. `OceanDepths` and `OceanDepthsCache` have something to do with sampling the height in the shader code and I believe a half float is being used.

Once the depths can be read at every point in the texture the jobs system will be complete. It super fast to grab thousands of points for your floating boat.

``` // Code to read off the texture caches
            RenderTexture renderTexture = newCache.CacheTexture;
            RenderTexture activeTexture = RenderTexture.active;

            Texture2D texture = new Texture2D(renderTexture.width, renderTexture.height, TextureFormat.R16, false, true);
            Rect rectReadPicture = new Rect(0, 0, renderTexture.width, renderTexture.height);
            RenderTexture.active = renderTexture;

            // Read pixels
            texture.ReadPixels(rectReadPicture, 0, 0);
            texture.Apply();

            RenderTexture.active = activeTexture; // added to avoid errors 
            Color[] readMap = texture.GetPixels(0, 0, texture.width, texture.height);
            float[] simpleCache = new float[readMap.Length];

            byte[] bytes;
            bytes = texture.EncodeToPNG();
            //System.IO.File.WriteAllBytes(Application.dataPath + "/texture.png", bytes);

            for(int i = 0; i < readMap.Length; i++)
            {
                float redChannel = readMap[i].r;

                // ????
                // here we need to convert the r channel to the depth in meters. Positive for deeper.

                simpleCache[i] = 1000;
            }
```

**Comment by huwb** [comment]
Hey sorry this has given you so much trouble.

Unity might be doing a conversion to/from srgb and clamping the values. Can you read them back as floats instead of using readpixels? (I don't know if this is possible)

**Comment by huwb** [comment]
I think you should make an async readback request using unity's API. there is example usage of it in the GPU readback stuff in crest. If your texture is R16 format you should get an array of ushort values back like i do. You can then sample it like so:

            public bool SampleR16(ref Vector3 i_worldPos, out float depth)
            {
                if (!Valid) { depth = 0f; return false; }

                float xOffset = i_worldPos.x - _renderData._posSnapped.x;
                float zOffset = i_worldPos.z - _renderData._posSnapped.z;
                float r = _renderData._texelWidth * _renderData._textureRes / 2f;
                if (Mathf.Abs(xOffset) >= r || Mathf.Abs(zOffset) >= r)
                {
                    // outside of this collision data
                    depth = 0f;
                    return false;
                }

                var u = 0.5f + 0.5f * xOffset / r;
                var v = 0.5f + 0.5f * zOffset / r;
                var x = Mathf.FloorToInt(u * _renderData._textureRes);
                var y = Mathf.FloorToInt(v * _renderData._textureRes);
                var idx = (y * (int)_renderData._textureRes + x);
                depth = Mathf.HalfToFloat(_data[idx + 0]);

                return true;
            }

I think _renderData._posSnapped is the center of the texture in world space. It then converts it to a uv, and it assumes that the texture is axis aligned in the world (not rotated) which may not be the case with the cache..

**Comment by KellanHiggins** [comment]
@huwb Doing the API callback did the trick! I have successfully completed getting the ocean depth. Only downside is there is about 4 frames right at the start before the waves are read completely by the jobs system. I am not sure the best way to fix this but it will have to do for now.

This is on my main master branch. It is still a bit messy, so maybe take a look and let me know what I need to clean up. 

https://github.com/KellanHiggins/crest-oceanrender

**Comment by KellanHiggins** [comment]
Fixed an issue where multiple segments weren't being calculated.

For your naming convention, can you confirm something

m_variableName is a member variable
s_variableName is a static member variable
_variableName is a private member
variableName is a scoped variable

Anything else I should know for aligning the language?

**Comment by huwb** [comment]
This is what crest uses:

_memberVariable
s_staticMemberVariable
scopedVariable

There are some more notes in the contributing.md file.

Can you create a PR, that has an overview of the what/why/how of these changes. That will be a good place for us to discuss the changes.

It makes sense to make the PR against the branch feature/gerstner-jobs . I've updated this branch to latest. I think it would make sense to do an update on your side before creating the PR. That way we'll only see the changes that you've added, instead of also getting a bunch of changes in the difference between two versions.

A question i'll have is how to handle multiple depth caches. Thats a concern for merging into master, as it will generate confusion and bug reports. However it would still be valuable to offer this in a branch the way the gerstner job stuff is right now with this fact communicated so that anyone grabbing it knows the limitation.

**Comment by huwb** [comment]
Oh btw i'm update the feature/gerstner-jobs branch to latest. I can also help with your stuff getting on the same version etc if it helps, i think i have permission to push to forks.

**Comment by huwb** [comment]
I just updated the feature/gerstner-jobs branch to latest from master. Incidentally i updated the unity version on this branch to 2019.1.3 (from 2019.1.0) but not really on purpose and if thats annoying you can revert the last change to the projectversion.txt, as that was the only thing that changed in the upgrade.

**Comment by KellanHiggins** [comment]
I've merged the origin features branch of the jobs into my own branch of the gerster jobs. Just reviewing the style stuff right now.

The caches are written to the gerster jobs static singleton when they are generated by your code. If there are two depth caches that are overlapping then it uses the shallower depth between the two caches to figure out the depth. Works fine with many caches.

I am using the latest Unity 2019.1.5f, but it won't matter for this stuff. Should work fine on 2019.1.0

I will create a PR as soon as I can figure out how to do that.

**Comment by huwb** [comment]
Ok sure, thanks

I messed around and after a couple of false starts i think i have a PR set up

https://github.com/huwb/crest-oceanrender/pull/268

It wont merge as it doesnt have the latest from feature/gerstner-jobs from this repos (i updated it with the latest from master recently).

I thought i would try to be helpful and merge it in for you, and i did so, but now it seems like i can't push to your repos, and i dont really understand why as i have pushed changes to forks in the past. Log error when i try to push:

To https://github.com/KellanHiggins/crest-oceanrender.git
 ! [remote rejected]   KellanHiggins_feature/gerster-jobs -> feature/gerster-jobs (permission denied)
error: failed to push some refs to 'https://github.com/KellanHiggins/crest-oceanrender.git'

So i guess in this case since i cant help you upgrade your branch, could you do it? That means doing a pull of the latest from feature/gerstner-jobs in this repos, and merge it up. The merge didnt have any savagely bad conflicts but takes a little bit of time to go through the bits. Do you know how to do this? I'm not sure i've done this before, and probably wouldnt remember even if i had, but @moosichu gets along with git better than i do and might be able to help.

One alternative is to make me a collaborator in the repository settings on your side so i can push to your fork (hopefully!?) so then i'd be able to push the merge i did...

**Comment by huwb** [comment]
Just reread you last comment - maybe you already did the merge but haven't pushed it yet. Ignore me if so!

**Comment by KellanHiggins** [comment]
@huwb I'll try and pull in your stuff right now.

**Comment by KellanHiggins** [comment]
@huwb I've given you access to my fork as a contributor. I am not sure why there are merge conflicts on the pull request. I've pulled in your repo from the origin including the feature branch and I have no conflicts on my side.

I realize that the boat probes don't work with the ocean depth yet because I haven't modified their code. Do you want me to do that?

I will also put together an outline of the changes I made and post it on the pull request.

**Comment by KellanHiggins** [comment]
Nevermind, the boat probes are working great :). Looks like everything is good. I don't think "Boat Align To Normal" is working with jobs, but that is fine as I don't need that. Instead just need it for those complex boat points.

**Comment by KellanHiggins** [comment]
Aha, I hadn't pulled in your changes into my branch in a while. Did it now and it seems to be working. I resolved all the conflicts. I think we can take this to the PR now.
