### ISSUE TITLE
Strange shadowing issue near edges of camera view

### ISSUE THREAD

**Issue by jjxtra** [huwb/crest-oceanrender#255]
I've attached a screenshot. You can see at the edges the shadow is not showing and has a jagged edge. It is really bad if I turn the camera fast and takes a few hundred milliseconds to fade to the correct shadow... I've injected shadows with the storm clouds using Weather Maker, but this problem happens even if I simply edit the UpdateShadow.shader file and simply return a small value for the shadow, like 0.1.

![image](https://user-images.githubusercontent.com/1271832/57974893-0992cf80-797d-11e9-89ab-4003bd535bef.png)

**Comment by huwb** [comment]
Unfortunately this is a "feature" - the shadow cascade data is not available outside the frustum. 

There might be a way to artificially expand the cascade shadow map so that crest can get more data, but i don't know it.

The alternative is to not use crest shadow data at all and just sample shadows directly in the shader. i had a bad time trying to do this with the built-in render pipeline, the SRP may afford more flexibility here.

**Comment by jjxtra** [comment]
I'm not so sure the cascade shadowmap is the issue. Try returning a value like 0.1 hard-coded in the shadow shader. You will still see a problem on the edges and in the distance.

**Comment by huwb** [comment]
I added a commit to your PR which "addresses" it. It uses the undisplaced location to sample the shadow. I decided to push it your way instead of going straight to master as i could use a second pair of eyes, let me know what you think.

**Comment by jjxtra** [comment]
Ok will have a look now.

**Comment by jjxtra** [comment]
It looks a lot better. Things are still bright in the distance even with a hard-coded shadow value in the shadow shader, but this is progress!
