### ISSUE TITLE
Works with Android Vulkan but Not with OpenGL 3.2 ?

### ISSUE THREAD

**Issue by LIVENDA** [huwb/crest-oceanrender#258]
Works fine with Vulkan on Android but not with OpenGL 3.2 ?

**Comment by huwb** [comment]
Not sure off the top of my head, apologies. If you can fill the fields from the template then I might be able to assist.

**Comment by LIVENDA** [comment]
Describe the bug
Working fine with Vulkan on Android 8.0. With OpenGL 3.2, the ocean has no displacement however everything else works such as reflections, foam, caustics, ocean mesh and Lods



Versions
Unity 2019.1.0f3 , Android platform using OpenGL 3.2

To Reproduce
How can the developers reproduce this bug?

Deploy on an Android device supporting OpenGL 3.2

Are you able to reproduce the issue in the example content/scenes?
Yes

Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.
Android build target

Platform
Android

Editor or standalone?
Android .apk

**Comment by huwb** [comment]
I guess you're on this github version and not on Crest LWRP.

Is there any errors/warnings in the log?

**Comment by LIVENDA** [comment]
Yes, using the Github version, no errors in the log. Does LWRP version work with OpenGL?

**Comment by skaughtx0r** [comment]
I experienced a similar bug with master branch on Linux with OpenGLCore. The dynamic waves seem to grow indefinitely. It also seems that GPUReadback is unsupported in OpenGL, so this screenshot was taken with CPU collision.

I tried doing a Player build with Vulkan and everything seems to work just fine. It's probably not even worth targeting OpenGL due to lack of GPUReadback.

![Screenshot from 2019-05-27 08-49-53](https://user-images.githubusercontent.com/780663/58429990-7f252c80-805c-11e9-9e88-67cfc7a80b51.png)

**Comment by huwb** [comment]
I've not extensively tested on opengl and mobile. Having said that i had it running on my NexusX some weeks back. I guess that's 3.1..

This was on this commit: https://github.com/huwb/crest-oceanrender/commit/0d77cbc9a7ad116aa8c80b4ab911e6190ea70176

I'll post back when I find time to run tests on my side

**Comment by huwb** [comment]
We don't actively support OpenGL. It might be that it can be made to work with some fixes, but we are deprioritising supporting this platform.
