### ISSUE TITLE
Any lod count <7 breaks the cpu height system

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#265]
You can see in main test scene if lod count <7 the boat doesnt rock back and forth its just stationary

**Comment by huwb** [comment]
It seems to work for me for 5 & 6.

For 4 the available lods are quite small and the boat won't move due to the minObjectWidth setting in the animated wave settings, which is an optimisation that stops readback of small textures. By default its set to 3 which is wider than the row boat. If I set this to 0 or reduce it then i get the floating behaviour back.

**Comment by huwb** [comment]
Closing for now, let me know if it should be reopened
