### ISSUE TITLE
Velocity of interaction objects

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#36]
I've got a wave interaction object on our character to create waves while running or swimming through water.  I'm finding that once I get something which looks pretty good, it can go crazy when something gives the player an uncommonly high velocity (like falling from a high location, getting knocked back, falling from a fast-moving object, etc).

I feel like I need some way to clamp the velocity for the simulation on a per-object basis.  Because for small objects, the dynamics is mostly just for aesthetics, so we don't ever want the waves to get big enough to have a significant impact on the simulation.

Thanks!

**Comment by huwb** [comment]
Yeah this was sloppy - sorry for that.

I've added a clamp, and a teleport detection so that if the object is placed it won't generated ripples. I've set some defaults, if you have any feedback about these let me know. I also added a toggle for turning on warnings when the velocity is clamped or discarded.

These seem to help a lot for robustness - good shout with this request!

**Comment by Midda-C** [comment]
Nice, that did the trick!  Thanks a bunch, you work quick! :D
