### ISSUE TITLE
Garbage production

### ISSUE THREAD

**Issue by JJarvis89** [huwb/crest-oceanrender#37]
Hi, 

first of all, excellent work so far, I'm really liking what I'm seeing. I've been playing around with some of the examples and noticed in the profiler that a lot of garbage is being produced. I'm sure you are already aware of this. I just wanted to know if you plan on optimizing this any time soon?

Keep up the good work!

Best regards

**Comment by huwb** [comment]
Thanks! I'm really enjoying working with such a nice community :).

I had checked some time ago and i remember seeing some garbage produced but not finding many easy wins for avoiding it. However a lot of code has been added and removed since and I'll definitely dive back in and see where its at, and report back. I have a couple of things i need to look at first but will leave this open so its on my list. Thanks for raising it!

**Comment by huwb** [comment]
So it turns out there was a lot of garbage and some easy wins to avoid a bunch of it! And the fixes so far made the code better in a few ways so it was a good exercise.

I pushed progress so far in the fix/garbage_free branch. Accordingly to the memory section of the profiler, GC memory allocations per frame have dropped from 90kb to 24kb.

In the hierarchy view the remaining non-0 garbage allocations stacks appear to be:

5.5KB in ShapeGerstnerBatched.LateUpdateMaterials :(. I believe this can be mostly solved - I'm lazily adding/removing command buffers willy nilly and paying the cost in garbage. It will take some care to sort this out and I did not get around to this yet, i'll leave this issue open until it is sorted.
0.6 KB in Ocean Debug GUI - due to 2 string format operations. I'm not sure if i can get around this? In any case this is debug only so I will let this slide if need be.
384 B in GUI.Repaint. I turned off the debug GUI and it didnt go away. Might be an editor thing?
80 B in RenderPipelineManager.CleanUpRenderPipeline - I assume this is unity overhead, or a result of me adding/removing command buffers as described above.

**Comment by huwb** [comment]
Fixed all the garbage, except the small amount in the ocean debug GUI which I don't think i can fix easily, and I'm willing to live with i think.

In my tests it all seems to work. One of the changes may affect the ocean shape ( d1e794a257788338cc024541f27e9a435db61e85 ), i've contacted one of the teams to give them a heads up and will get this merged in when i hear back.

**Comment by huwb** [comment]
Should be done and dusted now! I'll try to keep better track of it in the future. Thanks again for raising.
