### ISSUE TITLE
Foam fade shore vs waves.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#40]
Probably want to give us two different settings for this.  In our project we want to control shore foam separate from the waves.  We like a little foam near the shore but always showing where the waves might have a bit more or less going on depending.

I think maybe there is away to do this with two different foam sims but so far no luck on that.  Though to be honest I dont think I fully understand what the res elements totally do.  Are they related to distance from the camera?  Wave Spectrums?  Maybe a little more info on how those work.  Will look through the rest of this and see if I can find the details.

Thanks

**Comment by huwb** [comment]
Yeah this could make sense - ill give it some more thought and get back to you.

I'd like to make a diagram to how visually what the lods are.. i'll think about what to do here.

**Comment by huwb** [comment]
I referenced this in my latest reply on #33, could you have a look when you get a chance?

Regarding your question..

The res elements determined which levels of detail (LODs) the simulations would run at. In the latest on master i have killed this setting completely so you're not faced with this non-trivial choice! it will automatically run sims at the current lod levels.

I'm not sure if the LODs in general are clear? My siggraph course describes the LOD'd structure http://advances.realtimerendering.com/s2017/index.html , and a good analogy that has occurred to me since is cascaded shadow maps, where are large area of the world are covered by multiple overlapping shadow map textures. this is exactly what crest achieves with multiple lods - detail close to the viewer + wide range/coverage of the world. an extra bit of magic sauce in crest dynamically chooses the lod resolutions based on how close you are to the surface - if you're not close to the surface it will pick larger lods and consequently cover a much larger area so you don't notice the extents of the waves.

also i've updated the oceandebuggui (example content) on the latest on master, the Show Sim Data now shows all the various sims and inspecting these may help to understand the structure.

i'm also aware a good diagram could be worth a thousand words here, its on my list..

**Comment by huwb** [comment]
Hi there, you refer to this in #33 but I didnt fully understand, could you please elaborate? How were you running two sims? Did you create a new sim type?

**Comment by huwb** [comment]
Wow, i had not realised adding two of the same kind of sim was possible! That's blowing my mind right now.

I had not anticipated using high foam fade rates, I have to admit you and @Midda-C have surprised me with this. I guess its because you guys want a stylised look/behaviour for the foam. There are settings for the shoreline foam gen but I'm sure you're already aware of them (Shoreline Foam Max Depth, Shoreline Foam Strength).

In this kind of scenario I am tempted to actually allow you to add multiple sims. Perhaps you could provide the simulation shader you want to use, so you could use one combined sim or use multiple sims that simulate specific elements. I'll ponder further and maybe sketch something out and get back to you.

**Comment by huwb** [comment]
Well this could be pretty sweet - you could define your own sims by defining just a few details and providing the sim shader:

![image](https://user-images.githubusercontent.com/939901/44507058-f5aa8d80-a6ca-11e8-8b4f-8aa42e9ef669.png)

This could be awesomely flexible - fingers crossed it works out!

**Comment by huwb** [comment]
I got a prototype working which allows you to create a new sim using data only, and I created a new shoreline foam sim. The two red sims in the debug overlay are both foam but one is shoreline and one is waves.

![image](https://user-images.githubusercontent.com/939901/44519136-f30d5f80-a6ed-11e8-8ff2-a02d894b5adb.png)

This approach has pros and cons .. I'll need to spend some more quality time with it and see how it evolves, no eta on getting this anywhere near usable yet!

**Comment by holdingjason** [comment]
Well do not push it if its a square peg round hole situation.  I was only using the two sims because it worked around the problem, had no idea only one foam sim was suppose to be running ha.  All the other changes you have made allow me to have something workable.  I can't speak for @Midda-C but I can get some white caps now while still having some pile up on the shore.  Its not perfect because as you said the higher my fade rate the less the shore foam, inverse relationship, so at really high rates you basically will not see any well defined shore line foam.  But as I drop it down to have a nice foam accumulation at the shore, but very close to shore and not far out, then we start to lose the strong lined white caps and they become more and more dragged out behind the wave.   I have found a decent sweet spot right now that works alright but yes it would be nice to have some way to have higher fade rates in the ocean while allowing less fade at shore which is what I was accomplishing with the two overlapping sims.

**Comment by holdingjason** [comment]
Looks like the latest build from this morning broke Shoreline Foam Max Depth.  On my build it does nothing ie foam shows up at what appears to be max depth no matter what the setting is.

**Comment by holdingjason** [comment]
Also not sure if this is new or related to the max depth but waves now stop at the point of where the shoreline foam starts I may just not have noticed this before since I had the Max Depth pretty close to shore if so then its fine..

**Comment by holdingjason** [comment]
Here is a link showing the issue.  Cannot get this foam back towards shore, waves die at the farthest foam point, also bubbles are maxed out as well as you can see out to that farthest point.

https://drive.google.com/open?id=1Hgdk8pBLNGU3_9rQ51xqqX94ady9rKbp

**Comment by holdingjason** [comment]
More info.  So playing with it you do not see it in your demo because I think my shoreline drops off slower and is a bit more shallow.  It does not seem to be picking up the drop off for some reason.

**Comment by huwb** [comment]
Crap that's my bad.. broke that recently while doing a cleanup - passed the wrong transform position, so the sea level was wrong in the depth cache. D'oh! Sorry! Thanks for tracking that down, nicely done!

FWIW i've moved everything in my main scene up by 5 units, so i will see issues like this in the future!

(Also, for the record, my beautiful 'data-driven sims' idea was a dead end eventually - it would take a bunch of work to add all the functionality required in a data-driven way, and even then it would require *some* code (mainly shader) and technical inputs that are not easy to author so i put that direction on ice for now - 9420b0792fab324c73545de908d9211535f4cbe1)

**Comment by holdingjason** [comment]
Bummer.  Ya with the new stuff the shore foam is still an issue.  I mean not a show stopper but at the higher foam fades (honestly anything above 5-6 the shore foam basically disappears so not great.  I wonder about a approach where we just completely fake it using a depth check and another texture as some of the water shaders do like the one below.  Not perfect by any stretch but just hucking ideas out.

https://assetstore.unity.com/packages/vfx/shaders/stylized-water-shader-71207
