### ISSUE TITLE
Broken prefabs in example content

### ISSUE THREAD

**Issue by huwb** [huwb/crest-oceanrender#51]
@Midda-C @holdingjason

Guys could you give me a bit more detail on what you see? Is it reporting that prefabs are "missing" in the threeboats scene? Which prefabs exactly?

So far i've tried the following to repro without success:

* Delete library folder and other generated data in my local workspace to trigger reimport - works fine
* Copy crest and crest-examples from my local workspace to a new unity project - all scenes fine (after layers added)
* Do a new fresh clone of the repos into a new folder - works fine (warning about extra meta file which i've fixed now)
* Create another new unity project, copy crest and crest-examples folders in from the new clone - all scenes fine after layers added
 
Note that i copy the meta files along with the folders - so Crest.meta and Crest-Examples.meta.

I'm on 2018.2.1f1. I'm happy to upgrade forward if you guys are on a new version.

**Comment by Midda-C** [comment]
Okay, so here's what I can repro it (though it sounds like you've already done this).  I'm on 2018.1.6f1 on this machine.

I downloaded the latest data from Github, extracted the Asset folder containing the Crest and Crest-Examples folders into an empty folder.  I opened that folder in Unity as a new project.

Firstly, in the log, I get meta file warnings that you mentioned, so that's no biggie.  Next, I open up the threeboats scene, and the scene heirarchy looks like this:

![image](https://user-images.githubusercontent.com/37893722/44401810-31dad280-a593-11e8-8c26-f6d0835800bb.png)

That's to be expected if the prefabs have been deleted or somthing, but what's odd is that I can still find the prefabs in the project window, under the boat folder.  But, what's even weirder is this, which I have never seen in Unity before.  When I click on the BoatAlignNormal prefab in the project view, this is what's in the inspector:

![image](https://user-images.githubusercontent.com/37893722/44401895-78303180-a593-11e8-9823-e6a93cbbc4a1.png)

Notice, at the top, right under where it has the tag and layer dropdowns.  It just—unhelpfully—says "missing", which makes no sense, because the prefab is clearly there, with all of its data, and I can expand it and look at all of the subobjects.

I also can't drop it into the scene view—just doesn't do anything, and the cursor turns into a cross.  If I try to drop it into the scene heirarchy, I get this:

```
Unable to instantiate prefab. Prefab may be broken.
UnityEditorInternal.InternalEditorUtility:HierarchyWindowDrag(HierarchyProperty, Boolean, HierarchyDropMode)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

So I'm really not sure what to do here.  It could be that I'm not on 2018.2 yet?  We'll be upgrading at some point, but you've been on 2018.2 for a few weeks now, right?  If so, I wouldn't have thought it'd be that, but who knows.

I hope this is helpful in some way, even though it sounds like you've already done exactly this.

**Comment by holdingjason** [comment]
Very odd @Midda-C .  I am not seeing this at all.  Everything looks fine on two projects.  I do blow out both directories completely when updating.  I am running on 2018.2.1f1 so ya maybe that is it.

**Comment by Midda-C** [comment]
Hmm, well all of the machines we've seen this on (three so far) have all been pre-2018.2, so maybe that's it.  Still an odd one.  I'll just upgrade my home machine to the latest version now and see if that's it.

**Comment by huwb** [comment]
Oh dear. There is a thread which indicates something along these lines: https://answers.unity.com/questions/1502308/missing-prefabs-after-downgrading-from-unity-20182.html

FWIW it seems updating forwards should work flawless but upgrading is one way and kills backwards compatibility (eeek).

That's quite a screw up.. and makes me tempted to downgrade back to 2018.1 and sit on that.. I guess I'll monitor for now, perhaps they manage to patch fix this in future versions.

Thanks, as always, for the help investigating..

**Comment by Midda-C** [comment]
Okay, well at least it's not technically a bug in Crest or our project, then!  We're not using any of the example prefabs in our project anyway, so it isn't a blocker for us—oh, and the issue @dizzy2003 was trying to fix when he found the broken prefabs is sorted now, anyway.

I see you've made note of it on the Readme.  Up to you if you want to close this issue or not.
