### ISSUE TITLE
Shader error in 'Ocean/Ocean Surface Alpha': undeclared identifier 'ComputeLodAlpha' at line 62 (on d3d11)

### ISSUE THREAD

**Issue by twobob** [huwb/crest-oceanrender#58]
Shader error in 'Ocean/Ocean Surface Alpha': undeclared identifier 'ComputeLodAlpha' at line 62 (on d3d11)

Google "ComputeLodAlpha", nothing.... any clues

Find all "ComputeLodAlpha", Find Results 1, Entire Solution, ""
  D:\Mirror\Unity-Projects-Folder\Cresty\Assets\Crest\Shaders\OceanSurfaceAlpha.shader(62):				float lodAlpha = ComputeLodAlpha(worldPos, _InstanceData.x);
  Matching lines: 1    Matching files: 1    Total files searched: 43

So.. what is it?  Built-in?  I'm using the wrong version? something?

**Comment by huwb** [comment]
Hi twobob!

Thats weird - thats a function in a file in the same folder as that shader. Heres the file in the repos:

https://github.com/huwb/crest-oceanrender/blob/master/src/unity/Assets/Crest/Shaders/OceanLODData.cginc

Do you have OceanLODData.cginc, does it match whats on git?

(btw disappointing that google does not index that!)

**Comment by twobob** [comment]
oh okay,,
I'll check that out

**Comment by twobob** [comment]
Hmm seems like 2.1.0 Is not doing the business.   
The cginc are missing?  Dunno.  I'll try the next release or something

**Comment by huwb** [comment]
Wow, thats really bad. Sorry you ran into this.

For some reason I'm not sure, the package generated badly. I just regenerated it now and it worked fine with default options so I'm not sure how it got messed up. Anyway as noted on the release, I have just regenerated the package: https://github.com/huwb/crest-oceanrender/releases/tag/2.1.0 . I have verified i can import it into a new project. It will complain at first about layers missing which need to be added, as instructed in the log, then it should work.

(Side note: the project has changed a LOT since that release, on the master branch. It's almost unrecognizable compared to latest. You might consider just downloading latest as a zip using the Clone or Download button on the main page: https://github.com/huwb/crest-oceanrender . In the meantime i'll consider making a new release to capture latest and greatest..)

**Comment by huwb** [comment]
After some consideration i decided now was the perfect time to make a new release! So find 3.0.0 here:

https://github.com/huwb/crest-oceanrender/releases/tag/3.0.0

I imported it into a new project and it worked fine except for a warning about an unassigned script - i added a note to the release about why this happens.

**Comment by huwb** [comment]
I'll assume this is solved but please let me know if you run into problems. Thanks for reporting!

**Comment by twobob** [comment]
Thanks Ill give it a look later tonight

**Comment by twobob** [comment]
![image](https://user-images.githubusercontent.com/915232/44960074-ab0dea00-aef0-11e8-9097-2540646b382f.png)
Works fine now.
That's circa 70 fps using the demo on an on-boad HD potato card.

nice one
