### ISSUE TITLE
Issues with Azure sky atmospheric scattering/fog

### ISSUE THREAD

**Issue by gamemachine** [huwb/crest-oceanrender#62]
Was testing against azure sky, and the water is blocking it's scattering and fog.  Anywhere water is rendered scattering/fog is gone.  Any geometry above the water gets scattering/fog applied correctly.

Any educated guess on what might be going on there?

**Comment by huwb** [comment]
Ha ok, one of the teams is using azure skies so it should work in theory..

Also i recently fixed a bug that broke the deferred fog - are you on latest from master, or the previous release? Here is the where it was reported and fixed: https://github.com/huwb/crest-oceanrender/issues/53#issuecomment-415774112

Otherwise please provide pictures if you can and any other relevant info. Are you using forward or deferred? Is azure providing the scattering and fog, or is it standard unity fog? I've never worked with the azure stuff so I'm a bit of a noob.

Thanks!

**Comment by huwb** [comment]
Thanks! Oh so Azure has its own version of fog? My guess would be that this does not work with transparents. If you made a huge transparent sphere above the island i guess it would not fog?

**Comment by gamemachine** [comment]
Transparent appears to work fine.  There is a large sphere between the camera and terrain in this pic.  I can barely make out an outline of it on my pc, appears to have no effect on fog.

![image](https://user-images.githubusercontent.com/75981/44901680-eb852200-acbc-11e8-9c0b-bc49f5cdc7bf.png)

**Comment by gamemachine** [comment]
FYI I have seen comments by the azure author re other waters about correctly rendering to the depth buffer.  Also his shader notes seem to indicate it's using the same core technique as the unity deferred fog.

**Comment by huwb** [comment]
Sorry for this menial sounding request but could you make the sphere 80% opaque and put it back to where the island is? I'm a bit confounded as to how this works. Is it a standard unity material set to Transparent?

In the last couple of weeks i made the changes necessary to get crest working with unity's deferred fog. Even in deferred rendering, the water is rendered in a forward manner, but is fed fog data to do the fogging itself. Generally transparents cannot just be fogged once in a deferred way - imagine you could make 5 overlapping spheres which can't be fogged in a deferred way, because it will all be collapsed down to one layer at the point that shading occurs. This is a core, fundamental issue with deferred rendering which is at the heart of this issue.

I don't think forcing depth on is going to help in deferred situations - i tried this and unity is like "ok you want to write to depth, i'm going to sneakily copy out the deferred depth BEFORE you start writing!!". this is again due to the problem of deferred not working if there are multiple transparent layers. It could help in forward rendering situations though - but it does not come without its own side effects!

I did a quick bit of googling and found this post so far: https://forum.unity.com/threads/azure-sky-dynamic-skybox.322773/page-4#post-2532897 . It suggests adding some code to the shader to do the fogging in a forward way which was my only idea so far - add some code to the ocean shader which does the Azure fogging.

However this may be shortcomings in my understanding, I appreciate the help talking this through. There are also some others we can consult who are using Azure but i'm not sure if they use the fogging component of it.

**Comment by gamemachine** [comment]
Ya this is standard shader set to transparent.

![image](https://user-images.githubusercontent.com/75981/44904888-4b7fc680-acc5-11e8-8bdf-05ce17e50ea6.png)

**Comment by gamemachine** [comment]
Found this maybe it's useful. 
https://forum.unity.com/threads/writing-to-depth-buffer-with-custom-shader.217814/#post-2724985

**Comment by gamemachine** [comment]
Tried adding a shadow pass no effect, well other then messing up the ocean rendering.  But seems to not help fog at all.

**Comment by huwb** [comment]
Is that working? The sphere didn't look like it's picking up the scattering, I was expecting it to be shortly blue... but it might just be the image. Pushing it further back and/or making the sphere a more different colour would be useful to see?

**Comment by holdingjason** [comment]
Hi just saw this.  Yep we are seeing the same thing.  Just noticed it.  Normal fog, deferred fog etc using postprocessing v2 works fine but not azures fog stuff.  Ocean ignores it.  Honestly not sure we are going to use there fog anyway so need to test with some others like HX Volumetric and Weather Maker.

Played around with it briefly but so far not really sure what is happening.

**Comment by holdingjason** [comment]
Ok confirmed this is not just an issue with AzureSky.  @huwb  you can repro this simply by using the standard assets GlobalFog.

I am including it here.  Just two scripts and a shader.  Also a nice image to show the issue.  Just add this to your camera and your good to go.

[Standard Assets.zip](https://github.com/huwb/crest-oceanrender/files/2341250/Standard.Assets.zip)

![image](https://user-images.githubusercontent.com/42001313/44931219-c244b000-ad15-11e8-9487-bc7198ea05f1.png)

**Comment by holdingjason** [comment]
Normal fog from lighting works fine btw.  Need to check the volumetric fog system and see how they go like I mentioned.

**Comment by gamemachine** [comment]
Tested this with the Volumetric fog and mist asset.  It results in the entire water being clipped.  It has a compute depth toggle which if toggled on removes the clipping and then exhibits the same behavior as Azure.

Tested Enviro same behavior as Azure.

**Comment by angry-penguin** [comment]
I'm also testing out Crest and using Azure Sky. I haven't got to testing sky integration in particular yet, but I think it's worth pointing out with regard to the sphere screenshot earlier that Azure does _not_ support fog scattering with transparent objects with the standard shaders. Until recently it didn't support fog with transparent objects at all.

For transparency support you need to use one of the provided transparent shaders with fog support, or follow provided instructions (which I haven't checked out) to add fog support yourself. The author mentions this [here](https://forum.unity.com/threads/azure-sky-dynamic-skybox.322773/page-16#post-3607516).

I suspect that this will be a similar case across the board with any fog system for reasons huwb [mentioned earlier](https://github.com/huwb/crest-oceanrender/issues/62#issuecomment-417602843).

**Comment by huwb** [comment]
Thanks guys, angry penguin you have unconfused me!

Ok guys please follow the instructions provided in the Azure sky package to add fogging to the ocean shader. The ocean shader has scene depth in the code which should be enough I would guess, but if you need anything else I'm happy to help if I can. (But I don't know if it's ok to post Azure sky code of it's not public, obviously, so perhaps take care here).

If someone does it and can give feedback on whether it was easy/hard and what was involved, please do share! And feel free to share screenshots :).

Is that reasonable? I'll leave this issue open for now in case I'm missing something.

**Comment by huwb** [comment]
So Denis Lemos (the Azure[Sky] developer) has very kindly demonstrated what is required to add the Azure scattering to Crest. See his reply here:

https://forum.unity.com/threads/azure-sky-dynamic-skybox.322773/page-17#post-3630571

He includes a version of the ocean shader with the lines added with comments referring to Azure. I don't anticipate that the steps will change much, if it does I'll update this thread accordingly.

Thanks for reporting and I'm happy to see it working - looks really nice!

**Comment by angry-penguin** [comment]
I saw that. Huge thumbs up to you both for being so responsive!

**Comment by huwb** [comment]
I've now added a comment calling out specifically where the azure code should be added for applying the fog. If it is just added at the end of the shader, it will mess with the underwater effect. See the above referenced commit.
