### ISSUE TITLE
Issues with physics on larger ships

### ISSUE THREAD

**Issue by FuriousChad** [huwb/crest-oceanrender#64]
Hello, I've been toying with the BoatAlignNormal.cs file on trying to figure out how to tweak the properties to fit heavier, larger ships. I can't seem to get realistic buoyancy physics despite any changes I make to the properties, and including modifying mass and drag on the Rigidbody.

**Comment by huwb** [comment]
Hi @FuriousChad , thanks for getting in touch.

I'll start off with the huge disclaimer - the buoyancy stuff in *BoatAlignNormal* is rough and unrealistic - it tries to approximate floating dynamics by sampling the normal at the position of the boat and aligning the boat to the water surface using forces. This is not how buoyancy works. There is an article https://www.gamasutra.com/view/news/237528/Water_interaction_model_for_boats_in_video_games.php that covers the physics and a potential implementation, or there are Asset Store plugins which do floating physics. I'm not sure if I'm likely to work on a proper buoyancy simulation any time soon.

**However** having said all of the above, there are some things that will help the simplistic physics approximate a larger ship:

* Give the *Boat Width* parameter an accurate value, or go larger with it. The physics will ignore wavelengths that are small compared to this width, which will effectively filter them out, so if you pick a large value for this it will only take into account the long waves (not the sharp/small ones).
* Scale down *Buoyancy Torque* - this is the rotational force applied to the boat and is independent of mass (which is why modifying mass did not help)
* *Engine Power* and *Turn Power* probably want to be reduced - these are also mass independent

There are other params that could help but i think the above are the main ones. Let me know if you have any luck?

**Comment by HyroVitalyProtago** [comment]
@FuriousChad If you are interested to use the model in the gamasutra article, there is a unity tutorial here : https://www.habrador.com/tutorials/unity-boat-tutorial/. I currently trying to use it with crest. I just need to found how to implement a custom WaterController that can get the y pos of water from a world position and timeSinceStart...

**Comment by huwb** [comment]
Oh thats cool thanks for the note. I'm pretty sure we can get the WaterController stood up. I'll take a look some point soon but if you have specific questions about how to get at the height queries in Crest let me know..

(Spoiler: it is accessible through OceanRenderer.Instance.CollisionProvider , and best to set OceanRenderer._cachedCpuOceanQueries on the script to make the hieight queries fast).

**Comment by huwb** [comment]
Cool!!! This is very good news.

My bad about the cache, must have broke it during a refactor :( i just pushed a fix to master which should sort it, let me know.

**Comment by huwb** [comment]
I reached out to Erik Nordeus and he graciously gave the thumbs up to port an implementation of his floating physics to Crest 👍 . I will probably make a number of modifications to it before its ready to merge into the master branch, but in the meantime I've pushed a commit with the basic stuff ported across and a cube floating in the boat.unity scene - see the referenced commit above.

**Comment by gamemachine** [comment]
I'm voting for also keeping the existing buoyancy around.  Realistic is often not the best gameplay, depends on the game.  Like if you look at some of the best ocean ship games such as sea of thieves, not at all realistic.  Aligning to surface normals is I think a great starting point for non realistic buoyancy.

**Comment by huwb** [comment]
Thanks for the notes! The align to normal script is quite simple and can indeed be kept around.

After posting my last comment above, I grabbed the build from Erik's website and the ship buoyancy acts quite strange, the boats seem to spin on the spot for me. Also, as I hinted in my comment above the code needs a fair bit of work. This needs some focus and love, and has not turned out to be the slam dunk or quick win i initially hoped.

I've decided now to shift course - I'm going to spend time polishing the rendering (partly driven by issue 85, but things generally need a bit of TLC, guided by a strong visual target), and consolidating the existing Crest features. We've been adding features at a rate of knots and we now need to settle and document them, and look at making better example content that showcases the features.

I'll close for now but I'm keen to pick this up when the other parts of crest are in better shape in the future. If you guys push it forward in the meantime please do post!

**Comment by HyroVitalyProtago** [comment]
@huwb Thanks is a good idea to be more focused on polishing the rendering part before all.
If I have some time to optimize the buoyancy part, I will post progress here.

**Comment by huwb** [comment]
@FuriousChad - while looking into something I found the *Boat Width* parameter (on the BoatAlignNormal script) that i described above to be broken, and has probably been broken for a while :/. I've pushed a fix to master now in the above referenced commit - if you get latest now you should clearly see how this parameter. Sorry for the confusion this no doubt caused :(, I should have double checked it at the time..

**Comment by holdingjason** [comment]
Would there also be a good way to apply a particle effect at the peak of a certain wave spectrum?  My guess  it would be similar to when foam is created, wondering if there is some way to get access to that on the cpu side in some manor.  Do not need all of them just would create a nice visual effect.

**Comment by DEKAGATO** [comment]
Man, when i try to put BoatPhysics i catch a bug, it pretty weird when put more boats in a line, the first boat act normally but the rest slowly stand up. I try to dig deeper and it seem something relate to buoyancy force.

**Comment by huwb** [comment]
Hi @DEKAGATO - does it change when you move the camera closer? I'm working heavily on the collision system right now - evolving in PR #100 . I can emit a warning if the boat is off the edge of the LOD data which would have this effect. 

If its indepdent of camera, yes stepping through the BoatAlignNormal FixedUpdate() function with a debugger should shed light.

**Comment by DEKAGATO** [comment]
[https://drive.google.com/open?id=1cfsOlGLpE23eRr4RA_0TPkDny3Dw74TX](url)
it's not relate with camera position or LOD.

**Comment by huwb** [comment]
Sorry i havent been able to help more @DEKAGATO . I'm not sure what would cause that to happen.

**Comment by huwb** [comment]
Just a note, since BoatAlignNormal seems to be finding way more use than i initially planned, I have just done a big tidy up of the params and added some tooltips.

I also added an optional Boat Length alongside the Boat Width param. This is demo'd in the main.unity example scene - note the rowboat will now roll at a higher frequency than it will pitch, due to the dimensions of the boat.

ec895c0b406cb668dd539371ca1cb2a1716ea1f5
