### ISSUE TITLE
Shorelines Only Work On Mountains

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#7]
Shorelines only show up for mountains. Adding other objects doesn't generate any new shorelines, even duplicating mountains model doesn't help. Also, deactivating the mountains doesn't remove the shoreline.

Unity 5.6.5, 2017.3, 2018.1

**Comment by huwb** [comment]
Thanks for reporting this! This was quite a bug - actually the issue was that multiple things could not render ocean depth at the same time, they were stomp over eachother. I've now set the blend operation to Min which allows them to blend correctly for me.

Something else that is probably causing confusion - it only gathers a list of stuff to generate shorelines from in Start(). This means if you dupe the island a runtime you wont see it generating shorelines or modulating waves. This is for performance reasons only. I could add a flag to make it regen the list every frame, or think about other solutions..

Finally, its bad that im rendering the depth every frame for an island that is static. I want to look at adding a depth cache that you can place on the island so that it becomes a cheap texture copy instead of rendering thousands of verts.

**Comment by GeorgeDziov** [comment]
Looking quite great now! But objects other than mountains still do not have foam unfortunately.
I like that performance oriented approach though. Btw why not make it possible to regenerate the list via user made script command? Like, say, when I wanna spawn an object, I execute a line of code that regenerates the list. Just suggesting this as a temporary solution at least.

![2018-05-05 13 28 27](https://user-images.githubusercontent.com/15368122/39662755-8887bdd8-506f-11e8-9c7e-699f68dae4c4.png)

**Comment by huwb** [comment]
You're welcome! Thanks for the feedback!

I implemented the cached depth thing in f6a1edd75ec3913f6ae2e906cfbcdf42a17de38b . The IslandDepthCache GO has a gizmo that shows its extents and a resolution setting in the inspector - this will render ocean depths out once on startup and will reuse this data each frame instead of rendering the terrain over and over. However note I left support in for the RenderOceanDepth component so if any objects need to render each frame this is still supported.

**Comment by GeorgeDziov** [comment]
Just checked:

1) Cool trick! IslandDepthCache on statics + ROD on some moving stuff gives some big flexibility imo!
2) Foam works on everything now, cubes included
3) Thanks for keeping ROD, without it like fish outta water! 
4) Noticed Setup info update which is cewl! I copied ocean and ShapeRender from main scene to other scenes and called it a day before. 

One small question : is it possible to configure shoreline thickness? It's perfect on mountains but a bit thin on almost everything else. I also saw big part of foam is hidden under object so I made a bigger invisible copy (cube, sphere, cylinder, some random mesh thing) to make bigger foam which looks not bad to be honest but that's a solution only for simple objects I guess (really sorry for stretching the topic).

**Comment by huwb** [comment]
Nice!

Yeah I've been meaning to add that but just needed someone to ask :). I added it in b25c99abee6292cec9182552fdda4d20582953b5 , but it's a global setting and I'm not sure it's going to do what you're hoping for and we might have to think about changing how foam is authored or adding other workflows. Let me know how you get on with it?

**Comment by GeorgeDziov** [comment]
Yeah big pity it's a global setting, still glad you added this, adds a lot to flexibility!
