### ISSUE TITLE
Short big jumps in water velocity and height changes

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#94]
I am seeing brief pops in water and height checks that are very large causing any buoyancy script to pop the object/jitter.  Will work fine for few seconds and then pop.  You can see this, as an example, in the boat align normal script.

Here I am dumping out values from the velWater vector.  The distance also jumps regardless of which distance method I am using ie the ones in boatalign script or sampleHeight.  Seems completely random.

(-0.4, 8.7, -3.1)
(-0.8, 7.0, -2.7)

BOING
(21.9, -27.1, -5.9)
(-0.4, 16.2, -5.9)
(-24.2, 38.9, 1.2)

(-1.2, 6.3, -2.7)
(-1.6, 6.4, -3.1)

Here is a video of it happening.

https://drive.google.com/open?id=1LKf6uOvhXcI-588N6qnvFz6-hYDuTYSL

Weight is set to 1.0 in Shape Gerstner Batched and here is spectrum I am using.

https://drive.google.com/open?id=1a7V5lHP--XaCz6QFQ9fyk_FJ1zZlWWv0

**Comment by holdingjason** [comment]
Just fyi I am seeing this issue even dropping weight down to 0.5 and using the WavesModerateSmooth

**Comment by holdingjason** [comment]
Ok still happens with new build.  It "appears" to get worse by increasing minSpatialLength though I still see it with lower values just not as bad.  So at 32 for instance you will get those sever pops.  I am trying to basically ignore everything other then the large waves so that is why that value is so high btw.

**Comment by huwb** [comment]
Thanks for reporting, thats not great!

Just to check, is this something new or have you seen this issue in the past?

Do you think it would occur in the example scenes as well, like boat.unity?

This is an almost useless test but if you have the ocean debug gui could you disable "Readback coll data" and confirm there are no more pops? (the collision will no longer match the render surface but thats fine for this test). One other question also on the debug gui - what do you see for "Coll Queue Lengths" ?

I checked here and it looks ok, but thats just on my laptop. I have some ideas but would like to nail down some of the above info before going further.

**Comment by holdingjason** [comment]
Pretty sure we have seen this for awhile.  I think we thought it was something on our side that was causing it but now I believe it was this issue.  It is not super bad with low Boat Width settings so a bit hard to notice.  One of our guys was always complaining the boat find of bounced around to much at random times so I finally just started digging into it.

I am using the boat scene to replicate with latest.  Just change Boat Width to 32 and you should see it right away.  You can also use the modified wave spectra here that we are using since it might be a combo issue.

https://drive.google.com/open?id=1flZzjjD4FFu2bEtziVFGmtLMUynVHEU6

**Comment by holdingjason** [comment]
As far as turning off readback the boat just sits there an no longer moves at all.

Col queue lengths are [2, 2]

**Comment by holdingjason** [comment]
Just curious if you can repro this or if you need more info.  The issue is pretty bad for us right now.  Either we get a boat that if effected by a lot of the waves and gets tossed around in deep sea action or we can ignore those waves (width value around 40) but get pops that shoot us into the sky etc.

**Comment by huwb** [comment]
Good(ish) news - i tried with your wave settings and boat width 32 and i see the boat bouncing a bit - not on the magnitude you describe but its something to go on at least. I thought with such a large width that maybe there was no lod big enough to give that resolution, but i put breakpoints in a few places to check and they did not get hit so I'm not sure.

Anyway at least i can see something on my side and i hope to get some time to drill down on this soon. I'll report back when i do.

**Comment by holdingjason** [comment]
Great thanks for the help.  Let me know if you need a better example that really pops it and I can shoot you over one.  Probably also has to do with the size of the collider on the rigidbody etc as well since that would effect how much the pop effects the rigidbody.

**Comment by huwb** [comment]
Ok the issue seems to be from the computation/estimation of the water surface velocity. This does a finite difference on the surface displacement which is super susceptible to any jitter. I have an idea where the jitter is coming from and will look into it.

For now I have created a new branch which has this computation disabled - option *Compute Water Vel* on the boat script. could you check that this resolves the issue for you, to make sure I'm on the right track? If it doesnt, could you capture a video with Debug Draw turned on the boat script and with the scene view visible? It will draw the relevant information that should make it possible to diagnose any remaining jitter from video.

One possibility is to just leave this option Compute Water Vel off if it resolves the jitter for you, however the boat will behave a bit differently on the water (it won't get pushed around with the water motion).

**Comment by holdingjason** [comment]
Not sure yet.  I am appear to still be getting issues with my boat but checking it out with yours and just comparing to make sure something I am doing is not creating an issue.  One thing I do notice however is just with your demo ie boat changing the width to 40 instead of 32 does cause yours to jump way up in the air replicating what I was seeing.  Not sure if 40 is somehow over some limit or something but thought I would mention it as I am testing other stuff here.

**Comment by holdingjason** [comment]
So this would work it appears.  Let me bang on it a bit more to make sure.  Does kind of suck that we would not have the nice push around motion which is really nice I will say however given the option between the two the jitter is just unworkable so that would be ok.

**Comment by huwb** [comment]
Hey, i spent the day on it and found a glorious infestation of bugs. The floating physics never really got stretched/battle tested until now i guess. I'll start writing up a summary of what i've found now and post shortly

**Comment by holdingjason** [comment]
Ok great, well great that you are finding issues and I am not crazy :)  Was just going to post that I was wrong.  Looked ok sitting there but when we started driving the boat around it went nuts.  Started jumping into the air etc, jumping waves etc so no bueno.

**Comment by holdingjason** [comment]
thanks as always for jumping into this.  Fantastic package we just absolutely love what you have done, nothing like this anywhere so thanks again.

**Comment by huwb** [comment]
Fixes that have gone into fix/boat-instabilities:

* Interpolation added - up until now the wave shape was point sampled. This was fine for using the more detailed lods but giving a boat width of 32 makes the steps really obvious. A useful test is to set Gravity to 0 which freezes the waves and makes this obvious. Performance: this is something to keep an eye on- manually implementing bilinear interpolation generates a surprising amount of code.. and requires 4 reads instead of 1.
* Time stamps recorded with the readback requests so that a velocity can be computed with an accurate DT. Also, I'm computing directly in the readback component instead of in the boat, which is more robust to various things. It requires a bit more CPU memory but i doubt this will make an impact, and there are ways to optimize this down if we need to.
* When lods changed scale, i was computing velocity across two different scales causing the huge spikes in velocity. I now ensure the scale matches the expected and the spikes are gone. The lods change scale based on the viewer - the camera. This is an interesting point - if you get weirdness try freezing the camera position.
* Removed a frame of latency for the physics wave shape, for free (yay)
* Added even more debug - an option that draws crosses in the area around the boat.

For me it now works better than i expected, even in very large choppy waves. Also i was worried that perhaps the async readbacks were dodgy or unreliable, but that doesnt seem to be the case so far, I've managed to make things pretty solid, so thats great.

Thats all the good news. There is one remaining instability, also related to lods changing scale / camera position. I'm still sometimes using read back data at the wrong lod scale, because readbacks come a frame or two later and the lods can change in the meantime. I need a good way to find the right readback request - might need some arch change. I'll think about it.

However I think it is worth trying out for sure as i dont notice this instability if i dont have the debug vis turned on.

**Comment by huwb** [comment]
Fixes that have gone into fix/boat-instabilities:

* Interpolation added - up until now the wave shape was point sampled. This was fine for using the more detailed lods but giving a boat width of 32 makes the steps really obvious. A useful test is to set Gravity to 0 which freezes the waves and makes this obvious. Performance: this is something to keep an eye on- manually implementing bilinear interpolation generates a surprising amount of code.. and requires 4 reads instead of 1.
* Time stamps recorded with the readback requests so that a velocity can be computed with an accurate DT. Also, I'm computing directly in the readback component instead of in the boat, which is more robust to various things. It requires a bit more CPU memory but i doubt this will make an impact, and there are ways to optimize this down if we need to.
* When lods changed scale, i was computing velocity across two different scales causing the huge spikes in velocity. I now ensure the scale matches the expected and the spikes are gone. The lods change scale based on the viewer - the camera. This is an interesting point - if you get weirdness try freezing the camera position.
* Removed a frame of latency for the physics wave shape, for free (yay)
* Added even more debug - an option that draws crosses in the area around the boat.

For me it now works better than i expected, even in very large choppy waves. Also i was worried that perhaps the async readbacks were dodgy or unreliable, but that doesnt seem to be the case so far, I've managed to make things pretty solid, so thats great.

Thats all the good news. There is one remaining instability, also related to lods changing scale / camera position. I'm still sometimes using read back data at the wrong lod scale, because readbacks come a frame or two later and the lods can change in the meantime. I need a good way to find the right readback request - might need some arch change. I'll think about it.

However I think it is worth trying out for sure as i dont notice this instability if i dont have the debug vis turned on.

**Comment by huwb** [comment]
Fixes that have gone into fix/boat-instabilities:

* Interpolation added - up until now the wave shape was point sampled. This was fine for using the more detailed lods but giving a boat width of 32 makes the steps really obvious. A useful test is to set Gravity to 0 which freezes the waves and makes this obvious. Performance: this is something to keep an eye on- manually implementing bilinear interpolation generates a surprising amount of code.. and requires 4 reads instead of 1.
* Time stamps recorded with the readback requests so that a velocity can be computed with an accurate DT. Also, I'm computing directly in the readback component instead of in the boat, which is more robust to various things. It requires a bit more CPU memory but i doubt this will make an impact, and there are ways to optimize this down if we need to.
* When lods changed scale, i was computing velocity across two different scales causing the huge spikes in velocity. I now ensure the scale matches the expected and the spikes are gone. The lods change scale based on the viewer - the camera. This is an interesting point - if you get weirdness try freezing the camera position.
* Removed a frame of latency for the physics wave shape, for free (yay)
* Added even more debug - an option that draws crosses in the area around the boat.

For me it now works better than i expected, even in very large choppy waves. Also i was worried that perhaps the async readbacks were dodgy or unreliable, but that doesnt seem to be the case so far, I've managed to make things pretty solid, so thats great.

Thats all the good news. There is one remaining instability, also related to lods changing scale / camera position. I'm still sometimes using read back data at the wrong lod scale, because readbacks come a frame or two later and the lods can change in the meantime. I need a good way to find the right readback request - might need some arch change. I'll think about it.

However I think it is worth trying out for sure as i dont notice this instability if i dont have the debug vis turned on.

**Comment by huwb** [comment]
You're welcome! So, fixes that have gone into fix/boat-instabilities:

* Interpolation added - up until now the wave shape was point sampled. This was fine for using the more detailed lods but giving a boat width of 32 makes the steps really obvious. A useful test is to set Gravity to 0 which freezes the waves and makes this obvious. Performance: this is something to keep an eye on- manually implementing bilinear interpolation generates a surprising amount of code.. and requires 4 reads instead of 1.
* Time stamps recorded with the readback requests so that a velocity can be computed with an accurate DT. Also, I'm computing directly in the readback component instead of in the boat, which is more robust to various things. It requires a bit more CPU memory but i doubt this will make an impact, and there are ways to optimize this down if we need to.
* When lods changed scale, i was computing velocity across two different scales causing the huge spikes in velocity. I now ensure the scale matches the expected and the spikes are gone. The lods change scale based on the viewer - the camera. This is an interesting point - if you get weirdness try freezing the camera position.
* Removed a frame of latency for the physics wave shape, for free (yay)
* Added even more debug - an option that draws crosses in the area around the boat.

For me it now works better than i expected, even in very large choppy waves. Also i was worried that perhaps the async readbacks were dodgy or unreliable, but that doesnt seem to be the case so far, I've managed to make things pretty solid, so thats great.

Thats all the good news. There is one remaining instability, also related to lods changing scale / camera position. I'm still sometimes using read back data at the wrong lod scale, because readbacks come a frame or two later and the lods can change in the meantime. I need a good way to find the right readback request - might need some arch change. I'll think about it.

However I think it is worth trying out for sure as i dont notice this instability if i dont have the debug vis turned on.

**Comment by huwb** [comment]
Sweet!

I started sketching out a rewrite that reads back only the LODs that are requested (could be a big improvement), and it keeps track of any readback data by resolution, so it's robust to lods changing scales etc. So far its going well - i like the affect on the code so far.

Not sure what we want to do right now though - may be worth me creating a PR with the changes so far, as I think i believe in these as being a good thing to push into master, even without the refactor.

**Comment by holdingjason** [comment]
Yep.  I would vote to push what you have done so far into master.  As you work on the rewrite in this (or another branch) I can help test that as well.
